version: '3.5'

# This compose file only works when used in conjunction with the default docker-compose file.
# docker compose -f docker-compose.yml -r docker-compose.api.yml

services:
    hardhat:
        container_name: thx_hardhat
        image: public.ecr.aws/o5j5y3t5/hardhat-thx-artifacts:4.0.4
        domainname: hardhat.thx.local
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        ports:
            - 8547:8545
        expose:
            - 8545
        environment:
            - VIRTUAL_HOST=hardhat.thx.local
            - VIRTUAL_PORT=8545

    nginx:
        image: nginx:1.17.10
        container_name: thx_nginx
        depends_on:
            - hardhat
        volumes:
            - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./certs/localhost.key:/etc/nginx/certs/nginx.key
            - ./certs/localhost.crt:/etc/nginx/certs/nginx.crt
        ports:
            - 8546:443
    api:
        container_name: thx_api
        build:
            context: .
            dockerfile: apps/api/Dockerfile
            target: develop
        env_file:
            - apps/api/.env.example
            - apps/api/.env.ci
        ports:
            - 3001:3000
        depends_on:
            - mongo
            - hardhat
