version: '3.5'

services:
    mongo:
        container_name: thx_mongo
        image: mongo
        env_file: .env.example
        restart: always
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
            MONGO_INITDB_DATABASE: admin
        volumes:
            - mongo-data:/data/db
            - ./fixture/db:/docker-entrypoint-initdb.d/fixture
            - ./scripts/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh

    nginx:
        image: nginx:1.17.10
        container_name: thx_nginx
        volumes:
            - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./certs/localhost.key:/etc/nginx/certs/nginx.key
            - ./certs/localhost.crt:/etc/nginx/certs/nginx.crt
        ports:
            - 8546:443

volumes:
    mongo-data:
