version: '3.8'

# This compose file only works when used in conjunction with the default docker-compose file.
# docker compose -f docker-compose.yml -f docker-compose.api.yml

services:
    api:
        container_name: thx_api
        build:
            context: .
            dockerfile: apps/api/Dockerfile
            target: develop
        volumes:
            - ./coverage/apps/api:/usr/src/app/coverage/apps/api
        env_file:
            - apps/api/.env.example
            - apps/api/.env.ci
        environment:
            HARDHAT_RPC: http://host.docker.internal:8545
            HARDHAT_RPC_TEST_OVERRIDE: http://host.docker.internal:8545
        ports:
            - 3001:3000
        depends_on:
            - mongo