version: '3.8'

volumes:
    nginx-shared-txs:
    nginx-shared-cfg:

services:
    nginx:
        container_name: thx_nginx
        image: nginx:alpine
        ports:
            - "${REVERSE_PROXY_PORT}:8000"
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - nginx-shared-txs:/nginx-txs
            - nginx-shared-cfg:/nginx-cfg
        depends_on:
            - txs-web
            - cfg-web
            - cgw-web

    txs-db:
        container_name: thx_safe_txs_db
        image: postgres:14-alpine
        environment:
            POSTGRES_PASSWORD: postgres
        volumes:
            - ./docker/data/txs-db:/var/lib/postgresql/data

    cfg-db:
        container_name: thx_safe_cfg_db
        image: postgres:14-alpine
        environment:
            POSTGRES_PASSWORD: postgres
        volumes:
            - ./docker/data/cfg-db:/var/lib/postgresql/data

    txs-redis:
        container_name: thx_redis
        image: redis:alpine

    txs-rabbitmq:
        container_name: thx_rabbitmq
        image: rabbitmq:alpine

    txs-web:
        container_name: thx_safe_txs_web
        image: safeglobal/safe-transaction-service:${TXS_VERSION}
        env_file:
            - docker/env/txs.env
        environment:
            - ETHEREUM_NODE_URL=${RUNNER_IP}
        depends_on:
            - txs-db
            - txs-redis
        working_dir: /app
        volumes:
            - nginx-shared-txs:/nginx
            - ./scripts/0074_insert_safe_master_copy.py:/app/safe_transaction_service/history/migrations/0074_insert_safe_master_copy.py
        command: docker/web/run_web.sh
        networks:
            - thx_network
                    
    txs-worker-indexer: &txs-worker
        container_name: thx_safe_txs_worker_indexer
        image: safeglobal/safe-transaction-service:${TXS_VERSION}
        env_file:
            - docker/env/txs.env
        environment:
            - ETHEREUM_NODE_URL=${RUNNER_IP}
            - RUN_MIGRATIONS=1
            - WORKER_QUEUES=default,indexing
        depends_on:
            - txs-db
            - txs-redis
        command: docker/web/celery/worker/run.sh

    txs-worker-contracts-tokens: 
        <<: *txs-worker
        container_name: thx_safe_txs_worker_contracts_tokens
        environment:
            - WORKER_QUEUES=contracts,tokens
            - ETHEREUM_NODE_URL=${RUNNER_IP}

    txs-worker-notifications-webhooks:
        <<: *txs-worker
        container_name: thx_safe_txs_worker_notifications_webhooks
        depends_on:
            - txs-db
            - txs-redis
        environment:
            - WORKER_QUEUES=notifications,webhooks
            - ETHEREUM_NODE_URL=${RUNNER_IP}

    txs-scheduler:
        <<: *txs-worker
        container_name: thx_safe_txs_scheduler
        depends_on:
            - txs-db
            - txs-redis
        command: docker/web/celery/scheduler/run.sh

    # Safe Config Service
    cfg-web:
        container_name: thx_safe_cfg_web
        image: safeglobal/safe-config-service:${CFG_VERSION}
        tty: true
        volumes:
            - nginx-shared-cfg:/nginx
        env_file:
            - docker/env/cfg.env
        depends_on:
            - cfg-db

    # Safe Client Gateway
    cgw-redis:
        container_name: thx_safe_cgw_redis
        image: redis:alpine

    cgw-web:
        container_name: thx_safe_cgw_web
        image: safeglobal/safe-client-gateway:${CGW_VERSION}
        env_file:
            - docker/env/cgw.env
        depends_on:
            - cgw-redis

    # ui:
    #     container_name: thx_safe_ui
    #     image: safeglobal/safe-wallet-web:${UI_VERSION}
    #     env_file:
    #         - docker/env/ui.env
    #     depends_on:
    #         - nginx
    #     ports:
    #         - "${REVERSE_PROXY_UI_PORT}:3000"
