name: E2E Tests

# on:
#     schedule:
#         - cron: '0 10 * * *'
on: [push]

jobs:
    e2e:
        name: 'E2E'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Chrome
              uses: cypress-io/github-action@v3
              with:
                  project: ./site
                  browser: chrome
                  start: yarn test:e2e
                  record: true
              env:
                  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
