name: E2E Tests

# on:
#     schedule:
#         - cron: '0 10 * * *'
on: [push]

jobs:
    e2e:
        name: 'E2E'
        runs-on: ubuntu-latest
        container: cypress/browsers:node16.14.2-slim-chrome103-ff102
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Install
              run: yarn

            - name: Chrome
              run: npx cypress run
              env:
                  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
