name: E2E CI

# on:
#     push:
#         branches:
#             - develop

jobs:
    tests:
        name: Playwright Run
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [16.x] # Add other versions if needed

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Install Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Restore Node.js dependencies
              uses: actions/cache@v3
              with:
                  path: ./node_modules
                  key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            - name: Install Node.js dependencies
              run: yarn install --frozen-lockfile

            - name: Cache Node.js dependencies
              uses: actions/cache/save@v3
              if: always()
              with:
                  path: ./node_modules
                  key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}

            - name: Install playwright browsers
              run: npx playwright install --with-deps

            - name: Run tests
              run: yarn playwright test
