name: E2E Tests

on:
    push:
        branches:
            - main
            - develop
    schedule:
        - cron: '0 4 * * *'

jobs:
    e2e:
        name: 'E2E'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install Node.js 16.x
              uses: actions/setup-node@v1
              with:
                  node-version: 16.x

            - name: Chrome install latest
              uses: browser-actions/setup-chrome@latest

            - name: Chrome set path
              run: echo "BROWSER_PATH=$(which chrome)" >> $GITHUB_ENV

            - name: Chrome E2E test 🚀
              id: 'test'
              uses: cypress-io/github-action@v4
              with:
                  install: true
                  record: true
                  browser: '${{ env.BROWSER_PATH }}'
              env:
                  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Update Discord
              if: always()
              env:
                  DISCORD_WEBHOOK: ${{ secrets.DISCORD_CYPRESS_WEBHOOK }}
              uses: Ilshidur/action-discord@master
              with:
                  args: "${{ steps.test.outcome == 'success' && '✅' || '⛔' }} E2EDev `develop`"
